version: "3"

services:
  app:
    build: .
    command: yarn start
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: github_client
      POSTGRES_USER: github_client_admin
      POSTGRES_PASS: github_client_password